config/routes.rb
Rails.application.routes.draw do
  root 'main#index'
  resources :abouts
  resources :about
  

end

app/models/about.rb
class About < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  before_action :set_about, only: %i[ show edit update destroy ]

  # GET /abouts or /abouts.json
  def index
    @about = About.all
  end

  # GET /abouts/1 or /abouts/1.json
  def show
  end

  # GET /abouts/new
  def new
    @about = About.new
  end

  # GET /abouts/1/edit
  def edit
  end

  # POST /abouts or /abouts.json
  def create
    @about = About.new(about_params)

    respond_to do |format|
      if @about.save
        format.html { redirect_to about_url(@about), notice: "About was successfully created." }
        format.json { render :show, status: :created, location: @about }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @about.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /abouts/1 or /abouts/1.json
  def update
    respond_to do |format|
      if @about.update(about_params)
        format.html { redirect_to about_url(@about), notice: "About was successfully updated." }
        format.json { render :show, status: :ok, location: @about }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @about.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /abouts/1 or /abouts/1.json
  def destroy
    @about.destroy

    respond_to do |format|
      format.html { redirect_to about_url, notice: "About was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_about
      @about = About.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def about_params
      params.require(:about).permit(:index)
    end
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  before_action :set_about, only: %i[ show edit update destroy ]

  # GET /abouts or /abouts.json
  def index
    @abouts = About.all
  end

  # GET /abouts/1 or /abouts/1.json
  def show
  end

  # GET /abouts/new
  def new
    @about = About.new
  end

  # GET /abouts/1/edit
  def edit
  end

  # POST /abouts or /abouts.json
  def create
    @about = About.new(about_params)

    respond_to do |format|
      if @about.save
        format.html { redirect_to about_url(@about), notice: "About was successfully created." }
        format.json { render :show, status: :created, location: @about }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @about.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /abouts/1 or /abouts/1.json
  def update
    respond_to do |format|
      if @about.update(about_params)
        format.html { redirect_to about_url(@about), notice: "About was successfully updated." }
        format.json { render :show, status: :ok, location: @about }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @about.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /abouts/1 or /abouts/1.json
  def destroy
    @about.destroy

    respond_to do |format|
      format.html { redirect_to abouts_url, notice: "About was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_about
      @about = About.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def about_params
      params.require(:about).permit(:index)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    flash[:notice] = "Logged in successfully"
    flash[:allert] = "Invalid email or password"
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/about/_about.html.erb
<div id="<%= dom_id about %>">
  <p>
    <strong>Index:</strong>
    <%= about.index %>
   
  </p>
 
</div>

app/views/about/_form.html.erb
<%= form_with(model: about) do |form| %>
  <% if about.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(about.errors.count, "error") %> prohibited this about from being saved:</h2>

      <ul>
        <% about.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :index, style: "display: block" %>
    <%= form.text_field :index %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/about/edit.html.erb
<h1>Editing about</h1>

<%= render "form", about: @about %>

<br>

<div>
  <%= link_to "Show this about", @about %> |
  <%= link_to "Back to abouts", abouts_path %>
</div>

app/views/about/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>About</h1>


<div id="abouts">
  <% @about.each do |about| %>
    <%= render about %>
    <p>
      <%= link_to "Show this about", about %>
    </p>
  <% end %>
</div>

<%= link_to "New about", new_about_path %>

app/views/about/new.html.erb
<h1>New about</h1>

<%= render "form", about: @about %>

<br>

<div>
  <%= link_to "Back to abouts", abouts_path %>
</div>

app/views/about/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @about %>

<div>
  <%= link_to "Edit this about", edit_about_path(@about) %> |
  <%= link_to "Back to abouts", abouts_path %>

  <%= button_to "Destroy this about", @about, method: :delete %>
</div>

app/views/abouts/_about.html.erb
<div id="<%= dom_id about %>">
  <p>
    <strong>Index:</strong>
    <%= about.index %>
   
  </p>
 
</div>

app/views/abouts/_form.html.erb
<%= form_with(model: about) do |form| %>
  <% if about.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(about.errors.count, "error") %> prohibited this about from being saved:</h2>

      <ul>
        <% about.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :index, style: "display: block" %>
    <%= form.text_field :index %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/abouts/edit.html.erb
<h1>Editing about</h1>

<%= render "form", about: @about %>

<br>

<div>
  <%= link_to "Show this about", @about %> |
  <%= link_to "Back to abouts", abouts_path %>
</div>

app/views/abouts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Abouts</h1>
<h1>About us</h1>

<div id="abouts">
  <% @abouts.each do |about| %>
    <%= render about %>
    <p>
      <%= link_to "Show this about", about %>
    </p>
  <% end %>
</div>

<%= link_to "New about", new_about_path %>



<!DOCTYPE html>
<html>
  <head>
    <title>CutefishOS – Cutefish OS Built on Ubuntu</title>

        <meta charset="utf-8" />
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0'>

    
    <meta name="description" content="Cutefish OS Built on Ubuntu">
    <meta property="og:description" content="Cutefish OS Built on Ubuntu" />
    
    <meta name="author" content="CutefishOS" />

    

    <!--[if lt IE 9]>
      <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    
    <link rel="stylesheet" type="text/css" href="/style.css" />
    <link rel="stylesheet" type="text/css" href="/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="alternate" type="application/rss+xml" title="CutefishOS - Cutefish OS Built on Ubuntu" href="/feed.xml" />
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-3075431923852009"
     crossorigin="anonymous"></script>
    <!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=G-PXWBYKLNGL"></script>
	<script>
  	window.dataLayer = window.dataLayer || [];
  	function gtag(){dataLayer.push(arguments);}
  	gtag('js', new Date());
  	gtag('config', 'G-PXWBYKLNGL');
	</script>
	<!-- Global site tag (gtag.js) - Google Analytics -->
	
    <!-- Created with Jekyll Now - http://github.com/barryclark/jekyll-now -->
  </head>

  <body>
    <div class="wrapper-masthead">
      <div style="padding: 0 10px;" class="container">
        <header class="masthead clearfix">
          <a href="/" class="site-avatar"><img src="https://raw.githubusercontent.com/cutefish-ubuntu/cutefish-ubuntu.github.io/master/branding/Cutefish-Logo.svg" /></a>

          <div class="site-info">
            <h1 class="site-name"><a href="/">CutefishOS</a></h1>
            <p class="site-description">Cutefish OS Built on Ubuntu</p>
          </div>

          <nav>
            <a href="/">Home</a>
            <!--<a href="/blog">Blog</a>-->
            <a href="/features">Features</a>
            <a href="/download">Download</a>
            <a href="/donate">Donate</a>
            <a href="/about">About</a>
          </nav>
        </header>
      </div>
    </div>

    <div id="main" role="main" class="container">
      <div class="head-img"> <img style="display: block; margin-left: auto; margin-right: auto;" src="https://raw.githubusercontent.com/cutefish-ubuntu/cutefish-ubuntu.github.io/master/images/home.a5604e32.png" alt="" width="50%" height="100%" /> </div>
<p style="font-weight: bold; text-align: center;"><strong><span style="font-size: 24pt;">Cutefish OS Built on Ubuntu</span></strong></p>
<p style="text-align: center;"><span style="font-size: 18pt;">Make a better experience Desktop OS </span>
	<br /><span style="font-size: 18pt;">Focus on simplicity, beauty and practicality</span></p>
<div style="text-align: center; padding-bottom: 20px;">
	<div class="download">
		<p style="margin: 5px 0;"><a href="/download">Try it</a></p>
	</div>
</div>

<div style="background: rgb(245, 245, 245) none repeat scroll 0% 0%;" class="row">
	<div style="max-width:1140px; margin:0 auto; padding-left:15px; padding-right:15px;">
		<div class="column"> <img src="https://raw.githubusercontent.com/cutefish-ubuntu/cutefish-ubuntu.github.io/master/images/color-wheel.f98f6e9e.svg" alt="" width="100%" height="100%" /> </div>
		<div class="column">
			<p><strong><span style="font-size: 18pt;">Better user experience</span></strong>
				<br />Simple and exquisite design, use the most suitable design to enhance user experience.</p>
		</div>
	</div>
</div>

<div style="background-image: linear-gradient(94.3deg,#1a2140 10.9%,#515473 87.1%);" class="row">
	<div style="max-width:1140px; margin:0 auto; padding-left:15px; padding-right:15px;">
		<div style="color: #ffffff;" class="column">
			<p><strong><span style="font-size: 18pt;">Security and stability</span></strong>
				<br />Cutefish OS is based on the open source Linux kernel. Linux is more secure than other operating systems. It has developers from all over the world to review its code and ensure that there are no bugs and backdoors.</p>
		</div>
		<div class="column"> <img src="https://raw.githubusercontent.com/cutefish-ubuntu/cutefish-ubuntu.github.io/39447f8811ae76d2f2973239beeb3e494dea8468/images/security.fa2043b9.svg" alt="" width="100%" height="100%" /> </div>
	</div>
</div>

<div style="background-image: radial-gradient(circle at 10% 20%, rgb(215, 223, 252) 0%, rgb(255, 255, 255) 0%, rgb(215, 223, 252) 84%);" class="row">
	<div style="max-width:1140px; margin:0 auto; padding-left:15px; padding-right:15px;">
		<div class="column"> <img src="https://raw.githubusercontent.com/cutefish-ubuntu/cutefish-ubuntu.github.io/master/images/apps.e5bc4f09.svg" alt="" width="100%" height="100%" /> </div>
		<div class="column">
			<p><strong><span style="font-size: 18pt;">Cutefish OS Applications</span></strong>
				<br />We have developed a series of Cutefish OS applications to ensure that users experience a unified UI / UX experience in their daily use.</p>
		</div>
	</div>
</div>

<div style="background-image: radial-gradient(circle farthest-corner at -8.9% 30.7%,#45f0b0 0,#365de4 90.5%);" class="row">
	<div style="max-width:1140px; margin:0 auto; padding-left:15px; padding-right:15px;">
		<div style="color: #fff;" class="column">
			<p><strong><span style="font-size: 18pt;">Open source</span></strong>
				<br />Cutefish OS is an open source project, anyone can understand how it works and participate in collaboration.</p>
		</div>
		<div class="column"> <img src="https://raw.githubusercontent.com/cutefish-ubuntu/cutefish-ubuntu.github.io/3b4919b44077ca7ee438e0e1673d111ae2e6ef76/images/opensource.e633ae41.svg" alt="" width="100%" height="100%" /> </div>
	</div>
</div>

<div style="background: linear-gradient(103.3deg, rgb(252, 225, 208) 30%, rgb(255, 173, 214) 55.7%, rgb(162, 186, 245) 81.8%);" class="row">
	<div style="max-width:1140px; margin:0 auto; padding-left:15px; padding-right:15px;">
		<div class="column"> <img src="https://raw.githubusercontent.com/cutefish-ubuntu/cutefish-ubuntu.github.io/master/images/desktop.9ec0c0ef.png" alt="" width="100%" /> </div>
		<div class="column">
			<p><strong><span style="font-size: 18pt;">Cutefish Desktop</span></strong>
				<br />Cutefish desktop environment is an efficient, beautiful, and modern desktop environment built using Qt Quick and some KDE basic frameworks.</p>
		</div>
	</div>
</div>

<div style="background-image: radial-gradient(circle at 10% 20%, rgb(215, 223, 252) 0%, rgb(255, 255, 255) 0%, rgb(215, 223, 252) 84%);" class="row">
	<div style="max-width:1140px; margin:0 auto; padding-left:15px; padding-right:15px;">
		<div class="column">
			<p><strong><span style="font-size: 18pt;">Global Menu</span></strong>
				<br />Cutefish OS has a global menu at the top. It is a collection of all functions of an application, which is very convenient for the integration of apps functions with the system, and can save some screen space.</p>
		</div>
		<div class="column"> <img src="https://raw.githubusercontent.com/cutefish-ubuntu/cutefish-ubuntu.github.io/master/images/menubar.47ce40cd.png" alt="" width="100%" height="100%" /> </div>
	</div>
</div>
    </div>

<div class="wrapper-footer">

    <footer id="myFooter">
        <div class="footer-container">
            <div class="row">
                <div class="col-sm-3">
                    <h5>Menu:</h5>
                    <ul>
                        <li><a href="/">Home</a></li>
                        <!--<li><a href="/blog">Blog</a></li>-->
                        <li><a href="/features">Features</a></li>
                        <li><a href="/download">Download</a></li>
                        <li><a href="/donate">Donate</a></li>
                        <li><a href="/privacy">Privacy & Cookies</a></li>
                        <li><a href="/about">About</a></li>
                    </ul>
                </div>
                <div class="col-sm-3">
                    <h5>Friends:</h5>
                    <ul>
                        <li><a href="https://jingos.com/">JingOS</a></li>
                        <li><a href="https://mpr.hunterwittenborn.com/">MPR</a></li>
                        <li><a href="https://github.com/makedeb">Makedeb</a></li>
                    </ul>
                </div>
                <div class="col-sm-3">
                    <h5>Community:</h5>
                    <ul>
                        <li><a href="https://sourceforge.net/projects/cutefish-ubuntu/">SourceForge</a></li>
                        <li><a href="https://t.me/cutefishos_ubuntu">Telegram Group</a></li>
                        <li><a href="https://t.me/cutefishos_ubuntu_chat">Telegram Chat</a></li>
                        <li><a href="https://discord.gg/tRXpm4JP">Discord</a></li>
                        <li><a href="https://github.com/cutefishos-ubuntu">GitHub</a></li>
                    </ul>
                </div>
                <div class="col-sm-3 info">
                    <h5>About:</h5>
                    <p> Cutefish OS is an elegant, beautiful and easy-to-use Linux desktop operating system. It runs Cutefish Desktop based on Ubuntu and has a modern style design. Our goal is to provide users with a comfortable interface design, better user experience and a better choice. </p>
                    <h5>Donate:</h5>
                <ul>
                    <li><a href="https://www.paypal.com/donate?hosted_button_id=S7WAC4BVRUAFJ">PayPal</a></li>
                    <li><a href="https://ko-fi.com/cutefishos">Ko-Fi</a></li>
                </ul>
                </div>
            </div>
        </div>
        <div class="second-bar">
           <div class="footer-container">
                <div style="text-align: left;">
                <a style="text-align: left;" href="/"> Cutefish OS Ubuntu </a>
                <div class="social-icons">
                    <a href="https://github.com/titenko" class="github"><i class="fa fa-github"></i></a>
                    <a href="https://t.me/maksymtitenko" class="telegram"><i class="fa fa-telegram"></i></a>
                    </div>
                </div>
            </div>
            <p style="text-align: center;">Cutefish OS Built on Ubuntu &copy; 2021-2022 Maksym Titenko</p>
            <p style="text-align: center;">Ubuntu is a Trademark of Canonical Ltd. CutefishOS is a Trademark of CutefishOS Team.</p>
            <p style="text-align: center;">Linux &reg; is the registered trademark of Linus Torvalds in the U.S. and other countries.</p>
        </div>
    </footer>
    </div>

    
	<!-- Google Analytics -->
	<script>
		(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

		ga('create', 'G-PXWBYKLNGL', 'auto');
		ga('send', 'pageview');
	</script>
	<!-- End Google Analytics -->


    
  </body>
</html>

app/views/abouts/new.html.erb
<h1>New about</h1>

<%= render "form", about: @about %>

<br>

<div>
  <%= link_to "Back to abouts", abouts_path %>
</div>

app/views/abouts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @about %>

<div>
  <%= link_to "Edit this about", edit_about_path(@about) %> |
  <%= link_to "Back to abouts", abouts_path %>

  <%= button_to "Destroy this about", @about, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScheduledTweets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render partial: "shared/navbar" %>

    <div class="container">
      <%= render partial: "shared/flash" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<div class="d-flex aling-items-center justify-content-center">
<h1>Bienvenidos a Autana Muebles</h1>
</div>
<p>Find me in app/views/main/index.html.erb</p>

<div class="container">
  <div class="notification is-primary">
    This container is <strong>centered</strong> on desktop and larger viewports.

		<div class="card">
		  <div class="card-image">
		    <figure class="image is-4by3">
		      <img src="https://bulma.io/images/placeholders/1280x960.png" alt="Placeholder image">
		    </figure>
		  </div>
		  <div class="card-content">
		    <div class="media">
		      <div class="media-left">
		        <figure class="image is-48x48">
		          <img src="https://bulma.io/images/placeholders/96x96.png" alt="Placeholder image">
		        </figure>
		      </div>
		      <div class="media-content">
		        <p class="title is-4">John Smith</p>
		        <p class="subtitle is-6">@johnsmith</p>
		      </div>
		    </div>
		
		    <div class="content">
		      Lorem ipsum dolor sit amet, consectetur adipiscing elit.
		      Phasellus nec iaculis mauris. <a>@bulmaio</a>.
		      <a href="#">#css</a> <a href="#">#responsive</a>
		      <br>
		      <time datetime="2016-1-1">11:09 PM - 1 Jan 2016</time>
		    </div>
		  </div>
		</div>




  </div>
</div>

app/views/shared/_flash.html.erb
<%if flash[:notice] %>
    <div class="alert alert-info mt-4" role="alert">
        <%=flash[:notice] %>
    </div>
<% end %>

<%if flash[:alert] %>
    <div class="alert alert-warning mt-4" role="alert">
        <%=flash[:alert] %>
    </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar is-transparent">
  <div class="navbar-brand">
    <a class="navbar-item" href="https://bulma.io">
      <img src="https://bulma.io/images/bulma-logo.png" alt="Bulma: a modern CSS framework based on Flexbox" width="112" height="28">
    </a>
    <div class="navbar-burger" data-target="navbarExampleTransparentExample">
      <span></span>
      <span></span>
      <span></span>
    </div>
  </div>

  <div id="navbarExampleTransparentExample" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item" href="https://bulma.io/">
        Home
      </a>
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link" href="https://bulma.io/documentation/overview/start/">
          Docs
        </a>
        <div class="navbar-dropdown is-boxed">
          <a class="navbar-item" href="https://bulma.io/documentation/overview/start/">
            Overview
          </a>
          <a class="navbar-item" href="https://bulma.io/documentation/overview/modifiers/">
            Modifiers
          </a>
          <a class="navbar-item" href="https://bulma.io/documentation/columns/basics/">
            Columns
          </a>
          <a class="navbar-item" href="https://bulma.io/documentation/layout/container/">
            Layout
          </a>
          <a class="navbar-item" href="https://bulma.io/documentation/form/general/">
            Form
          </a>
          <hr class="navbar-divider">
          <a class="navbar-item" href="https://bulma.io/documentation/elements/box/">
            Elements
          </a>
          <a class="navbar-item is-active" href="https://bulma.io/documentation/components/breadcrumb/">
            Components
          </a>
        </div>
      </div>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="field is-grouped">
          <p class="control">
            <a class="bd-tw-button button" data-social-network="Twitter" data-social-action="tweet" data-social-target="https://bulma.io" target="_blank" href="https://twitter.com/intent/tweet?text=Bulma: a modern CSS framework based on Flexbox&amp;hashtags=bulmaio&amp;url=https://bulma.io&amp;via=jgthms">
              <span class="icon">
                <i class="fab fa-twitter"></i>
              </span>
              <span>
                Tweet
              </span>
            </a>
          </p>
          <p class="control">
            <a class="button is-primary" href="https://github.com/jgthms/bulma/releases/download/0.9.4/bulma-0.9.4.zip">
              <span class="icon">
                <i class="fas fa-download"></i>
              </span>
              <span>Download</span>
            </a>
          </p>
        </div>
      </div>
    </div>
  </div>
</nav>